# Generated by Django 3.2.2 on 2021-05-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='memo',
            new_name='yourid',
        ),
    ]
