# Generated by Django 3.2.2 on 2021-05-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210516_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='yourid',
            new_name='memo',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='name',
            new_name='title',
        ),
    ]
